version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile.dev
    volumes:
      - .:/app
      - app_data:/app/data
      - poetry_cache:/root/.cache/pypoetry
    environment:
      - FLASK_APP=src.backend.app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    command: python -m flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    command: npm start

  voicevox:
    extends:
      file: docker-compose.yml
      service: voicevox

  ollama:
    extends:
      file: docker-compose.yml
      service: ollama

networks:
  manzai-network:
    driver: bridge

volumes:
  app_data:
  ollama_data:
  voicevox_data:
  poetry_cache: 