version: '3.8'

services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    # 一時的にヘルスチェックを無効化
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:50021/speakers"]
    #   interval: 10s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 20s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # 一時的にヘルスチェックを無効化
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "curl -s http://localhost:11434/api/tags > /dev/null && echo 'OK' || exit 1"]
    #   interval: 15s
    #   timeout: 60s
    #   retries: 3
    #   start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    environment:
      - OLLAMA_MODELS=/root/.ollama/models

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - poetry_cache:/root/.cache/pypoetry
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=src.app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - VOICEVOX_URL=http://voicevox:50021
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_INSTANCE_TYPE=docker
      - OLLAMA_MODEL=gemma3:4b
    depends_on:
      - voicevox
      - ollama

volumes:
  ollama_data:
  poetry_cache: 